## Last commit: 2026-08-20 11:02:41 IST by admin
system {
    host-name srx-fw-01;
    root-authentication {
        encrypted-password "$6$abcd1234"; ## SECRET-DATA
    }
    login {
        idle-timeout 45;
        message "Unauthorized access prohibited";
        password {
            minimum-length 8;
        }
        user operator {
            uid 2001;
            class read-only;
        }
    }
    services {
        ssh {
            protocol-version v2;
            connection-limit 10;
            root-login deny;
        }
        telnet;
        web-management {
            http {
                interface ge-0/0/0.0;
            }
        }
    }
    syslog {
        host 10.20.0.50 {
            any notice;
        }
    }
    ntp {
        server 10.20.0.9;
    }
}
snmp {
    community public {
        authorization read-only;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 198.51.100.2/30;
            }
        }
    }
}
